
export default function Home() {
  return (
    <div>
      <h1 className="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Welcome!</h1>
      <p>Lorem ipsum odor amet, consectetuer adipiscing elit. Montes dictumst parturient aliquam ac justo dignissim. Facilisi fusce proin class fermentum magna hendrerit arcu natoque lectus. Turpis ad nec vehicula euismod gravida fringilla. Mi tellus consectetur pharetra tortor feugiat; potenti est urna ullamcorper. Venenatis risus sagittis nec feugiat est quis. Quisque luctus gravida porta condimentum fusce sagittis blandit. Morbi est himenaeos laoreet elementum faucibus proin cursus. Montes velit erat ultricies; convallis bibendum tempus ac.</p>
      <p>Natoque auctor cursus nunc tortor id velit eros tortor. Ultricies dui blandit euismod at nec quisque leo. Justo scelerisque massa hac finibus dignissim. Nulla ultrices integer torquent varius lobortis. Posuere laoreet fames phasellus, tempus ridiculus rutrum cubilia? Scelerisque felis orci; himenaeos auctor placerat mollis. Quam lectus sit purus; elementum montes consequat. Penatibus risus blandit facilisi enim sit parturient.</p>
      <p>Maecenas hendrerit tortor non nulla vivamus. Luctus himenaeos proin donec lacinia elementum pharetra. Taciti dictum integer nam auctor; leo litora adipiscing. Ut class sodales laoreet inceptos purus efficitur. Bibendum faucibus integer convallis lobortis odio adipiscing venenatis non! Potenti auctor rhoncus ullamcorper hendrerit ut vestibulum. Ultricies hac justo posuere nibh nostra sociosqu rutrum dignissim. Varius habitasse quam tristique nisl montes viverra. Fusce auctor primis litora dapibus vel morbi nisi tempus placerat. Id elementum magnis nam auctor class porta.</p>
      <p>Primis rutrum id accumsan iaculis est mattis eget himenaeos blandit. Torquent habitasse litora aliquet eleifend mattis placerat purus iaculis. Venenatis praesent efficitur nam quam praesent. Inceptos porttitor luctus volutpat cursus tellus placerat pulvinar. Viverra morbi torquent turpis quisque et. Leo tortor bibendum taciti fusce sit amet litora viverra at. Ad porta phasellus lectus; diam euismod ridiculus bibendum. Nibh tincidunt nibh penatibus nullam aliquet gravida quisque.</p>
      <p>Efficitur cras nascetur condimentum duis mauris facilisi tristique amet parturient. Cras sagittis montes metus aenean feugiat. Torquent semper accumsan non pretium metus amet massa. Lacus pellentesque malesuada vehicula justo scelerisque. Curae id urna dui mi non eget posuere. Torquent phasellus dictum nullam cubilia blandit ultrices fames lacinia. Iaculis duis scelerisque venenatis nam dis enim dis cursus semper. Accumsan dictum dui inceptos in orci urna.</p>
      
    </div>
  )
}